/* eslint-disable */
/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import { a } from "@aws-amplify/data-schema";
import { configure } from "@aws-amplify/data-schema/internals";
import { secret } from "@aws-amplify/backend";

export const schema = configure({
    database: {
        identifier: "IDBIfBY9scaE4ZZ74DDhaw",
        engine: "postgresql",
        connectionUri: secret("SQL_CONNECTION_STRING"),
        vpcConfig: {
            vpcId: "vpc-0a548d6bf3d23cef7",
            securityGroupIds: [
                "sg-0d3eb631cb1f83d91"
            ],
            subnetAvailabilityZones: [
                {
                    subnetId: "subnet-087236adbd42b70df",
                    availabilityZone: "us-east-1c"
                },
                {
                    subnetId: "subnet-02ad2dd53591c2f61",
                    availabilityZone: "us-east-1a"
                },
                {
                    subnetId: "subnet-0c668111d064c3676",
                    availabilityZone: "us-east-1b"
                },
                {
                    subnetId: "subnet-0152ebf60a8ea9d27",
                    availabilityZone: "us-east-1f"
                },
                {
                    subnetId: "subnet-00773f132836a03bc",
                    availabilityZone: "us-east-1e"
                },
                {
                    subnetId: "subnet-07c78999c661ebb33",
                    availabilityZone: "us-east-1d"
                }
            ]
        }
    }
}).schema({
    "users": a.model({
        id: a.integer().required(),
        name: a.string().required(),
        email: a.string().required()
    }).identifier([
        "id"
    ])
});
