/* eslint-disable */
/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import { a } from "@aws-amplify/data-schema";
import { configure } from "@aws-amplify/data-schema/internals";
import { secret } from "@aws-amplify/backend";

export const schema = configure({
    database: {
        identifier: "IDY3j70jLZ88KHQJ7JGjGQQ",
        engine: "postgresql",
        connectionUri: secret("SQL_CONNECTION_STRING"),
        vpcConfig: {
            vpcId: "vpc-0db83e96d794d81b7",
            securityGroupIds: [
                "sg-0c09bee5da4d3cf88"
            ],
            subnetAvailabilityZones: [
                {
                    subnetId: "subnet-0949d91f208a6c9ef",
                    availabilityZone: "us-east-1b"
                },
                {
                    subnetId: "subnet-08a4a6d64b743004f",
                    availabilityZone: "us-east-1f"
                },
                {
                    subnetId: "subnet-03e00c60772268ddd",
                    availabilityZone: "us-east-1e"
                },
                {
                    subnetId: "subnet-04959daa6f22f497c",
                    availabilityZone: "us-east-1a"
                },
                {
                    subnetId: "subnet-0ab2678e011395b9d",
                    availabilityZone: "us-east-1d"
                },
                {
                    subnetId: "subnet-081b5564204f97564",
                    availabilityZone: "us-east-1c"
                }
            ]
        }
    }
}).schema({
    "users": a.model({
        id: a.integer().required(),
        name: a.string().required(),
        email: a.string().required()
    }).identifier([
        "id"
    ])
});
